export const lang = {
    "en": {
        required: "This field is required",
        email: "This field requires a valid e-mail address",
        number: "This field requires a number",
        integer: "This field requires an integer value",
        url: "This field requires a valid website URL",
        tel: "This field requires a valid telephone number",
        maxlength: "This fields length must be < ${1}",
        minlength: "This fields length must be > ${1}",
        min: "Minimum value for this field is ${1}",
        max: "Maximum value for this field is ${1}",
        pattern: "Please match the requested format",
    },
    "fr": {
        required: "Ce champ est obligatoire",
        email: "Ce champ requiert une adresse e-mail valide",
        number: "Ce champ requiert un nombre",
        integer: "Ce champ requiert un nombre entier",
        url: "Ce champ requiert une URL valide",
        tel: "Ce champ requiert un numéro de téléphone valide",
        maxlength: "La longueur de ce champ doit être < ${1}",
        minlength: "La longueur de ce champ doit être > ${1}",
        min: "La valeur minimum pour ce champ est ${1}",
        max: "La valeur maximum pour ce champ est ${1}",
        pattern: "Veuillez respecter le format requis",
    },
    "es": {
        required: "Este campo es obligatorio",
        email: "Este campo requiere una dirección de correo electrónico válida",
        number: "Este campo requiere un número",
        integer: "Este campo requiere un número entero",
        url: "Este campo requiere una URL válida",
        tel: "Este campo requiere un número de teléfono válido",
        maxlength: "La longitud de este campo debe ser < ${1}",
        minlength: "La longitud de este campo debe ser > ${1}",
        min: "El valor mínimo para este campo es ${1}",
        max: "El valor máximo para este campo es ${1}",
        pattern: "Por favor, respeta el formato requerido",
    }
};
